version: '3.8'
services:
  app:
    image: node:latest 
    # user: node
    working_dir: /app
    volumes:
      - ./package.json:/app/package.json
      - .:/app
       
    command: sh -c "npm i && npm start"
    ports:
      - "3000:4200"
    restart: unless-stopped
        # depends_on:
        # networks:
        #     - proxy

  # traefik:
  #   image: traefik:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./traefik.yml:/traefik.yml:ro
  #     - ./certs:/certs

      #   labels:
      # - "traefik.http.routers.angular.rule=Host(`angularTest`)"
      # - "traefik.http.routers.angular.entrypoints=http"
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # - "traefik.http.routers.angular.middlewares=redirect-to-https"